### ISSUE TITLE
Issue with your library

### ISSUE THREAD

**Issue by Elegye** [SimonDuperray/MotionsBrightnessController#1]
This line does not work as expected : 
https://github.com/SimonDuperray/MotionsBrightnessController/blob/0fd86e2e29befc605df3af93864c330e713ac0b3/script.py#L1

Do not know why.

**Comment by SimonDuperray** [comment]
It should be ok now, can you confirm ?

**Comment by Elegye** [comment]
Lot better ! I close my issue and wish you a good day

**Comment by SimonDuperray** [comment]
Have a good day too :)
